"""Pure (de)serialization between a Decision and its markdown mirror document.

A document is YAML frontmatter (identity + human-owned scalar fields + read-only
machine fields) plus a markdown body (pattern, rationale). Read-only fields are
emitted so the audit/diff shows them, but parsing (added in a later task) must
never return them as editable.
"""
from __future__ import annotations

import hashlib
import json

import yaml
from metatron.models import Decision
from metatron.feedback_score import HelpfulnessScore


def render_document(d: Decision, helpfulness: HelpfulnessScore | None) -> str:
    fm = {
        "id": d.id,
        "scope": d.scope,
        "confidence": d.confidence.value,
        "source_refs": [r.ref for r in d.source_refs],
        # machine-owned (read-only): import must ignore changes to these
        "keywords": list(d.keywords),
        "helpfulness_score": round(helpfulness.score, 2) if helpfulness else None,
        "created_at": d.created_at.isoformat(),
        "updated_at": d.updated_at.isoformat(),
    }
    front = yaml.safe_dump(fm, sort_keys=False).strip()
    body = [
        "## Pattern", d.pattern, "",
        "## Rationale", d.rationale, "",
        "<!-- keywords / helpfulness_score / timestamps above are read-only:",
        "     machine-derived, regenerated by `metatron mirror sync` -->",
    ]
    return f"---\n{front}\n---\n\n" + "\n".join(body) + "\n"


def parse_document(text: str) -> dict:
    """Return ONLY human-owned fields from a mirror document.

    Machine-owned frontmatter (keywords, helpfulness_score, timestamps) is
    intentionally dropped so a hand-edit to it can never round-trip. Status is
    NOT here — it comes from the file's directory. Body sections map to
    pattern/rationale.
    """
    _, _, rest = text.partition("---\n")
    front_raw, _, body = rest.partition("\n---\n")
    fm = yaml.safe_load(front_raw) or {}
    out = {k: fm[k] for k in ("id", "scope", "confidence") if k in fm}
    if "source_refs" in fm:
        out["source_refs"] = fm["source_refs"]
    out["pattern"] = _section(body, "Pattern")
    out["rationale"] = _section(body, "Rationale")
    return out


def _human_projection(
    *, id, status_value, scope, confidence, pattern, rationale, source_refs
) -> str:
    """Stable JSON over exactly the human-owned, round-trippable fields.

    Machine fields (keywords, helpfulness_score, timestamps) are deliberately
    excluded: they drift on their own and would cause false conflicts.
    """
    return json.dumps(
        {
            "id": id,
            "status": status_value,
            "scope": scope,
            "confidence": confidence,
            "pattern": pattern,
            "rationale": rationale,
            "source_refs": list(source_refs or []),
        },
        sort_keys=True,
    )


def fingerprint_decision(d) -> str:
    """Human-field fingerprint of a live Decision (the export baseline)."""
    return hashlib.sha1(
        _human_projection(
            id=d.id,
            status_value=d.status.value,
            scope=d.scope,
            confidence=d.confidence.value,
            pattern=d.pattern,
            rationale=d.rationale,
            source_refs=[r.ref for r in d.source_refs],
        ).encode()
    ).hexdigest()


def fingerprint_fields(parsed: dict, status) -> str:
    """Human-field fingerprint of a parsed file + its directory-derived status."""
    return hashlib.sha1(
        _human_projection(
            id=parsed.get("id"),
            status_value=status.value,
            scope=parsed.get("scope"),
            confidence=parsed.get("confidence"),
            pattern=parsed.get("pattern"),
            rationale=parsed.get("rationale"),
            source_refs=parsed.get("source_refs", []),
        ).encode()
    ).hexdigest()


def _section(body: str, heading: str) -> str:
    lines = body.splitlines()
    try:
        start = lines.index(f"## {heading}") + 1
    except ValueError:
        return ""
    collected = []
    for line in lines[start:]:
        if line.startswith("## ") or line.startswith("<!--"):
            break
        collected.append(line)
    return "\n".join(collected).strip()
