"""Pure (de)serialization between a Decision and its markdown mirror document.

A document is YAML frontmatter (identity + human-owned scalar fields + read-only
machine fields) plus a markdown body (pattern, rationale). Read-only fields are
emitted so the audit/diff shows them, but parsing (added in a later task) must
never return them as editable.
"""
from __future__ import annotations

import yaml
from metatron.models import Decision
from metatron.feedback_score import HelpfulnessScore


def render_document(d: Decision, helpfulness: HelpfulnessScore | None) -> str:
    fm = {
        "id": d.id,
        "scope": d.scope,
        "confidence": d.confidence.value,
        "source_refs": [r.ref for r in d.source_refs],
        # machine-owned (read-only): import must ignore changes to these
        "keywords": list(d.keywords),
        "helpfulness_score": round(helpfulness.score, 2) if helpfulness else None,
        "created_at": d.created_at.isoformat(),
        "updated_at": d.updated_at.isoformat(),
    }
    front = yaml.safe_dump(fm, sort_keys=False).strip()
    body = [
        "## Pattern", d.pattern, "",
        "## Rationale", d.rationale, "",
        "<!-- keywords / helpfulness_score / timestamps above are read-only:",
        "     machine-derived, regenerated by `metatron mirror sync` -->",
    ]
    return f"---\n{front}\n---\n\n" + "\n".join(body) + "\n"
