from __future__ import annotations

from pathlib import Path

from metatron.filesfirst.document import parse_decision_file
from metatron.filesfirst.schema import RESERVED_FILENAMES

_HEADER = "# Decision index\n\n> Generated by `metatron files index` — do not edit by hand.\n\n"
_COLUMNS = "| id | status | title | keywords | refs |\n|---|---|---|---|---|\n"


def build_index(decisions_dir: Path) -> str:
    rows: list[str] = []
    for md in sorted(Path(decisions_dir).glob("*.md")):
        if md.name in RESERVED_FILENAMES:
            continue
        fm = parse_decision_file(md, md.read_text(encoding="utf-8")).frontmatter
        keywords = ", ".join(fm.get("keywords") or [])
        rows.append(
            f"| `{fm.get('id', '')}` | {fm.get('status', '')} | "
            f"{fm.get('title', '')} | {keywords} | {fm.get('references', 0)} |"
        )
    return _HEADER + _COLUMNS + ("\n".join(rows) + "\n" if rows else "")


def write_index(decisions_dir: Path) -> Path:
    out = Path(decisions_dir) / "index.md"
    out.write_text(build_index(decisions_dir), encoding="utf-8")
    return out
