from __future__ import annotations

from pathlib import Path

from metatron.filesfirst.document import parse_decision_file
from metatron.filesfirst.schema import RESERVED_FILENAMES

_HEADER = "# Decision index\n\n> Generated by `metatron files index` — do not edit by hand.\n\n"
_COLUMNS = "| id | status | title | keywords | refs | viol |\n|---|---|---|---|---|---|\n"


def build_index(decisions_dir: Path) -> str:
    rows: list[str] = []
    for md in sorted(Path(decisions_dir).glob("*.md")):
        if md.name in RESERVED_FILENAMES:
            continue
        doc = parse_decision_file(md, md.read_text(encoding="utf-8"))
        fm = doc.frontmatter
        kw = fm.get("keywords") or []
        if isinstance(kw, str):  # tolerate a scalar `keywords: auth` (lint flags it)
            kw = [kw]
        keywords = ", ".join(kw)
        rows.append(
            f"| `{doc.id}` | {fm.get('status', '')} | "
            f"{fm.get('title', '')} | {keywords} | {fm.get('references', 0)} | {fm.get('violations', 0)} |"
        )
    return _HEADER + _COLUMNS + ("\n".join(rows) + "\n" if rows else "")


def write_index(decisions_dir: Path) -> Path:
    out = Path(decisions_dir) / "index.md"
    out.write_text(build_index(decisions_dir), encoding="utf-8")
    return out
